apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"kibana-infra-v1"},"name":"kibana-infra","namespace":"es-cluster-infra"},"spec":{"ports":[{"port":5601,"protocol":"TCP","targetPort":"ui"}],"selector":{"app":"kibana-infra-v1"}}}
  creationTimestamp: "2021-10-26T13:18:49Z"
  labels:
    app: kibana-infra-v1
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":5601,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-10-26T13:18:49Z"
  name: kibana-infra
  namespace: es-cluster-infra
  resourceVersion: "133325363"
  selfLink: /api/v1/namespaces/es-cluster-infra/services/kibana-infra
  uid: 5702192e-cc8c-4bed-97b1-5c54ccab1b6f
spec:
  clusterIP: 10.43.168.118
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    app: kibana-infra-v1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
